"""Native Claude Code session titles (issue #85).

Two units:
- ``orchestrator_jsonl._build_summary`` extracts the LATEST ``{"type":"ai-title"}``
  record's ``aiTitle`` into ``summary["ai_title"]`` (auto-backfills old sessions).
- ``orchestrator_meta.resolve_title`` precedence:
    manual rename → native ai_title → stored title → first-message preview → "".
"""

import json

from orbit import orchestrator_jsonl as jsonl
from orbit import orchestrator_meta as meta


def _write(path, lines):
    path.write_text("".join(json.dumps(o) + "\n" for o in lines), encoding="utf-8")


def _user(text, ts="2026-06-15T10:00:00Z"):
    return {"type": "user", "timestamp": ts, "message": {"role": "user", "content": text}}


def _ai_title(title, sid="s1"):
    return {"type": "ai-title", "aiTitle": title, "sessionId": sid}


# ── _build_summary: native ai-title extraction ────────────────────────────
def test_build_summary_extracts_latest_ai_title(tmp_path):
    p = tmp_path / "s1.jsonl"
    _write(p, [
        _user("checkout to PR https://example.com/very/long/url/that/is/ugly"),
        _ai_title("Early working title"),
        _ai_title("Fix PR review comments"),  # latest wins
    ])
    s = jsonl._build_summary(p)
    assert s["ai_title"] == "Fix PR review comments"
    # the raw first-message preview is still captured as the fallback source
    assert s["first_user_preview"].startswith("checkout to PR")


def test_build_summary_preview_skips_local_command_and_bash_artifacts(tmp_path):
    # A session whose opening turns are a slash-command caveat + a `!`-run bash
    # command must NOT be titled "<local-command-caveat>…": the preview falls
    # through to the first REAL user message. (Issue #85 follow-up.)
    p = tmp_path / "s4.jsonl"
    _write(p, [
        _user("<local-command-caveat>Caveat: The messages below were generated by the user…</local-command-caveat>"),
        _user("<command-name>/plugin</command-name>"),
        _user("<bash-input>ls</bash-input>"),
        _user("<bash-stdout>app\nlib\nREADME.md</bash-stdout>"),
        _user("przejdź na branch związany z tym PR"),  # the real first message
    ])
    s = jsonl._build_summary(p)
    assert s["first_user_preview"] == "przejdź na branch związany z tym PR"
    assert "<local-command" not in s["corpus"]
    assert "<bash-" not in s["corpus"]


def test_build_summary_all_command_noise_yields_empty_preview(tmp_path):
    # No real prose at all → empty preview (UI shows "untitled"), never a caveat.
    p = tmp_path / "s5.jsonl"
    _write(p, [
        _user("<local-command-caveat>Caveat: …</local-command-caveat>"),
        _user("<bash-input>git status</bash-input>"),
    ])
    s = jsonl._build_summary(p)
    assert s["first_user_preview"] == ""


def test_build_summary_no_ai_title_is_empty_string(tmp_path):
    p = tmp_path / "s2.jsonl"
    _write(p, [_user("hello there")])
    s = jsonl._build_summary(p)
    assert s["ai_title"] == ""


def test_ai_title_record_does_not_corrupt_counts_or_created_at(tmp_path):
    # An ai-title line carries no timestamp/message — it must not be counted as
    # a message nor consumed as the "first" event for created_at.
    p = tmp_path / "s3.jsonl"
    _write(p, [
        _ai_title("Title first in file"),  # leading ai-title
        _user("real first message", ts="2026-06-15T12:34:56Z"),
        _ai_title("   "),  # whitespace-only → ignored, keeps prior value
    ])
    s = jsonl._build_summary(p)
    assert s["ai_title"] == "Title first in file"  # blank record didn't clobber it
    assert s["msg_count"] == 1  # only the user line counts
    assert s["created_at"] > 0  # taken from the user line, not the ai-title


# ── resolve_title: precedence ─────────────────────────────────────────────
def test_resolve_title_manual_rename_wins():
    assert meta.resolve_title(
        {"title": "My Rename", "title_manual": True},
        {"ai_title": "Native", "first_user_preview": "hi"},
    ) == "My Rename"


def test_resolve_title_native_beats_preview_and_nonmanual_stored():
    # no manual flag → native ai_title beats both a stored non-manual title…
    assert meta.resolve_title(
        {"title": "Stale Haiku", "title_manual": False},
        {"ai_title": "Native", "first_user_preview": "first msg"},
    ) == "Native"
    # …and the first-message preview
    assert meta.resolve_title(
        {}, {"ai_title": "Native", "first_user_preview": "first msg"},
    ) == "Native"


def test_resolve_title_falls_back_to_stored_then_preview_then_empty():
    # stored non-manual title used when there's no native title
    assert meta.resolve_title({"title": "Haiku"}, {"ai_title": ""}) == "Haiku"
    # preview when nothing else
    assert meta.resolve_title({}, {"first_user_preview": "first msg"}) == "first msg"
    # nothing at all
    assert meta.resolve_title({}, {}) == ""
    assert meta.resolve_title(None, None) == ""


def test_resolve_title_strips_and_ignores_blank_native():
    assert meta.resolve_title({}, {"ai_title": "  Spaced  "}) == "Spaced"
    # blank native falls through to preview
    assert meta.resolve_title({}, {"ai_title": "   ", "first_user_preview": "p"}) == "p"


def test_resolve_title_blank_manual_title_does_not_win():
    # title_manual set but title is blank → must not return "" prematurely;
    # falls through to the native title.
    assert meta.resolve_title(
        {"title": "   ", "title_manual": True}, {"ai_title": "Native"},
    ) == "Native"
